# http://github.com/docker/go
%global goipath         github.com/docker/go
%global commit          d30aec9fd63c35133f8f79c3412ad91a3b08be06

%gometa -i

Name:           golang-github-docker-go
Version:        1.5.1
Release:        0.10%{?dist}
Summary:        Go packages with small patches autogenerated
# Detected licences
# - BSD (3 clause) at 'LICENSE'
License:        BSD
URL:            %{gourl}
Source0:        %{gosource}
Patch0:         Fix-formatting.patch
Source1:        glide.lock
Source2:        glide.yaml

%description
%{summary}

%package devel
Summary:       %{summary}
BuildArch:     noarch

%description devel
%{summary}

This package contains library source intended for
building other packages which use import path with
%{goipath} prefix.

%prep
%gosetup
%patch0 -p1
cp %{SOURCE1} %{SOURCE2} .

%install
%goinstall glide.lock glide.yaml

%check
%gochecks

#define license tag if not already defined
%{!?_licensedir:%global license %doc}

%files devel -f devel.file-list
%license LICENSE
%doc README.md

%changelog
* Fri Jul 13 2018 Fedora Release Engineering <releng@fedoraproject.org> - Forge-specific packaging variables
- Rebuilt for https://fedoraproject.org/wiki/Fedora_29_Mass_Rebuild

* Sat Jun 09 2018 Jan Chaloupka <jchaloup@redhat.com> - 1.5.1-0.9.gitd30aec9
- Upload glide files

* Wed Feb 28 2018 Jan Chaloupka <jchaloup@redhat.com>
- Autogenerate some parts using the new macros

* Wed Feb 07 2018 Fedora Release Engineering <releng@fedoraproject.org> - 1.5.1-0.7.gitd30aec9
- Rebuilt for https://fedoraproject.org/wiki/Fedora_28_Mass_Rebuild

* Wed Aug 02 2017 Fedora Release Engineering <releng@fedoraproject.org> - 1.5.1-0.6.gitd30aec9
- Rebuilt for https://fedoraproject.org/wiki/Fedora_27_Binutils_Mass_Rebuild

* Wed Jul 26 2017 Fedora Release Engineering <releng@fedoraproject.org> - 1.5.1-0.5.gitd30aec9
- Rebuilt for https://fedoraproject.org/wiki/Fedora_27_Mass_Rebuild

* Fri Feb 10 2017 Fedora Release Engineering <releng@fedoraproject.org> - 1.5.1-0.4.gitd30aec9
- Rebuilt for https://fedoraproject.org/wiki/Fedora_26_Mass_Rebuild

* Thu Jul 21 2016 Fedora Release Engineering <rel-eng@lists.fedoraproject.org> - 1.5.1-0.3.gitd30aec9
- https://fedoraproject.org/wiki/Changes/golang1.7

* Tue Mar 15 2016 jchaloup <jchaloup@redhat.com> - 1.5.1-0.2.gitd30aec9
- Bump to upstream d30aec9fd63c35133f8f79c3412ad91a3b08be06
  related: #1313942

* Wed Mar 02 2016 jchaloup <jchaloup@redhat.com> - 0-0.1.gitbaf439e
- First package for Fedora
  resolves: #1313942
